# Ablation: No Skeleton Map (use latent images as ground truth)
# This config removes skeleton-based ground truth and uses latent-to-latent reconstruction.

data:
  path: "data/processed"
  batch_size: 16
  num_workers: 4
  shuffle: True

model:
  use_discriminator: false
  use_skeleton_target: false  # KEY CHANGE: Use latent as both input and target
  generator:
    in_channels: 1
    out_channels: 1
    features: [64, 128, 256, 512]
  discriminator:
    in_channels: 2
    features: [64, 128, 256, 512]

training:
  epochs: 50
  lr: 0.001
  beta1: 0.5
  beta2: 0.999
  reconstruction_weight: 0.001

output:
  save_dir: "models/ablation_no_skeleton/"
  save_interval: 10
  log_dir: "logs/ablation_no_skeleton/"
