# Ablation: No Orientation Field (remove orientation field input)
# This config removes orientation field from the input pipeline.

data:
  path: "data/processed"
  batch_size: 16
  num_workers: 4
  shuffle: True

model:
  use_discriminator: false
  use_orientation_field: false  # KEY CHANGE: Skip orientation field
  generator:
    in_channels: 1
    out_channels: 1
    features: [64, 128, 256, 512]
  discriminator:
    in_channels: 2
    features: [64, 128, 256, 512]

training:
  epochs: 50
  lr: 0.001
  beta1: 0.5
  beta2: 0.999
  reconstruction_weight: 0.001

output:
  save_dir: "models/ablation_no_orientation/"
  save_interval: 10
  log_dir: "logs/ablation_no_orientation/"
