# Ablation: No Minutia Weight (standard L1 loss instead of weighted)
# This config removes the skeleton/orientation field weighting from reconstruction loss.

data:
  path: "data/processed"
  batch_size: 16
  num_workers: 4
  shuffle: True

model:
  use_discriminator: false
  use_weighted_loss: false  # KEY CHANGE: Remove weighting
  generator:
    in_channels: 1
    out_channels: 1
    features: [64, 128, 256, 512]
  discriminator:
    in_channels: 2
    features: [64, 128, 256, 512]

training:
  epochs: 50
  lr: 0.001
  beta1: 0.5
  beta2: 0.999
  reconstruction_weight: 0.001

output:
  save_dir: "models/ablation_no_weight/"
  save_interval: 10
  log_dir: "logs/ablation_no_weight/"
