data:
  path: "data/processed"
  batch_size: 16
  num_workers: 4
  shuffle: True

model:
  generator:
    in_channels: 1
    out_channels: 1
    features: [64, 128, 256, 512]
  discriminator:
    in_channels: 2
    features: [64, 128, 256, 512]

training:
  epochs: 100
  lr: 0.001
  beta1: 0.5
  beta2: 0.999
  reconstruction_weight: 0.001

output:
  save_dir: "models/"
  save_interval: 10
  log_dir: "logs/"